package cabinet_management;

public enum Cat_Quest {
    STRUCTURE_FAMILIALE,
    DYNAMIQUE_FAMILIALE,
    ANTECEDENTS_FAMILIAUX,
    CONDITIONS_NATALES,
    DEVELOPPEMENT_PSYCHOMOTEUR,
    DAVELOPPEMNT_LANGAGIER,
    CARACTERE_COMPORTEMENT,
    HISTOIRE_MALADIE,
    SUIVI_MEDICAL

}
